[WIPAdd a VSCode .devcontainer
alan-turing-institute/data-safe-haven pull request #1328
Opened 2022-11-18 15:52 UTC by craddm

## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the **develop branch**.
- [x] Your branch is up-to-date with the **develop branch** (you probably started your branch from `develop` but it may have changed since then).
- [ ] If-and-only-if your changes are not yet ready to merge, you have marked this pull request as a **draft** pull request and added '[WIP]' to the title.
- [ ] If-and-only-if you have changed any Powershell code, you have run the code formatter. You can do this with `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>`.

### :arrow_heading_up: Summary

### :closed_umbrella: Related issues

Closes #1327 

### :microscope: Tests

2022-11-22 16:59 UTC, jemrobinson requested changes

2022-11-22 16:59 UTC, jemrobinson commented on .devcontainer/Dockerfile
> +#   && apt-get -y install azure-cli="${AZURE_CLI_VERSION}-1~buster"
Are these lines needed?

2022-11-22 16:59 UTC, jemrobinson commented on .devcontainer/install_pwsh_modules.ps1
> +}
This looks like a duplicate of the existing installation script. Is there a way we can define this all in one place? For example by copying the existing script into the devcontainer?

2022-11-22 16:59 UTC, jemrobinson commented on .devcontainer/requirements.txt
> +Sphinx==5.2.3
Same with these requirements - they look like a duplicate.

2022-11-23 13:10 UTC, jemrobinson approved these changes

2022-11-23 13:10 UTC, jemrobinson commented on .devcontainer/devcontainer.json
> +		"context": "..",
This is cool. I don't think Docker can include files from outside parent-of-Dockerfile natively :)

2022-11-23 13:11 UTC, jemrobinson commented on .devcontainer/devcontainer.json
> +		"context": "..",
This is cool. I don't think Docker can include files from outside parent-of-Dockerfile natively :). Merge whenever you're ready @craddm .

2022-11-23 13:11 UTC, jemrobinson approved these changes
This is cool. I don't think Docker can include files from outside parent-of-Dockerfile natively :). Merge whenever you're ready @craddm .

2022-11-23 14:43 UTC, craddm commented
I'm not authorized to merge! Yeah, I thought it needed those scripts to be in the same directory (or at least in a sub-directory) as the Dockerfile, but turns out you can just run `docker build` from the parent directory of the `.devcontainer` directory (if you want to build it manually rather than let VSCode do it) and then it handles the filepaths fine.

2022-11-23 16:10 UTC, merged