Factor out storage creation from SHM scripts
alan-turing-institute/data-safe-haven pull request #1673
Opened 2023-11-27 15:23 UTC by craddm

## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [ ] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [x] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

Moves the SHM storage account creation step into its own script, adds it as a step in the `Deploy_SHM.ps1` script

### :closed_umbrella: Related issues

Closes #1366 

### :microscope: Tests

Tested SHM deployment and storage account creation with new scripts.

2023-11-28 13:53 UTC, JimMadge requested changes
Looks good, one comment about help text.

2023-11-30 11:14 UTC, craddm commented
> Looks good, one comment about help text.

I can't see any comments or changes requested

2023-11-30 11:31 UTC, JimMadge commented
🤦

2023-11-30 11:33 UTC, JimMadge requested changes

2023-11-30 11:33 UTC, JimMadge commented on deployment/safe_haven_management_environment/setup/Setup_SHM_Storage_Accounts.ps1
> +    [Parameter(Mandatory = $true, HelpMessage = "Enter SHM ID (e.g. use 'testa' for Turing Development Safe Haven A)")]
I think "testa" and "Turing Development Safe Haven A" won't make sense to anyone apart from us (and it sort of implies that "testa" is translated to the full name somehow).

How do we describe SHM ID in other help text?

2023-11-30 13:46 UTC, craddm commented on deployment/safe_haven_management_environment/setup/Setup_SHM_Storage_Accounts.ps1
> +    [Parameter(Mandatory = $true, HelpMessage = "Enter SHM ID (e.g. use 'testa' for Turing Development Safe Haven A)")]
I see what you mean. The same help text is used everywhere, so will do a separate issue and change this in a separate PR

2023-12-01 11:17 UTC, JimMadge approved these changes

2023-12-01 11:18 UTC, merged