Restructure processes section of docs
alan-turing-institute/data-safe-haven pull request #1766
Opened 2024-03-27 10:01 UTC by JimMadge

## :white_check_mark: Checklist

- [ ] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [ ] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [ ] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [ ] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [ ] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

### :closed_umbrella: Related issues

Closes #1764 

### :microscope: Tests

2024-03-27 10:15 UTC, jemrobinson commented on docs/source/roles/investigator/data_egress.md
>  Once the classification is agreed, make sure that your {ref}`role_data_provider_representative` discusses the best way to extract your outputs from the environment with your {ref}`role_system_manager
References classification

2024-03-27 15:00 UTC, JimMadge commented
There will (almost certainly) be some references to roles/classification left.

2024-03-28 10:19 UTC, jemrobinson commented on docs/source/roles/investigator/data_egress.md
> +Once you have finished working with the data for your project, you'll have to conduct the egress any outputs of your work before the environment is shutdown.
+1 for removal of ingress/egress as verbs, but it might take a while to do this universally!

2024-03-28 12:27 UTC, craddm commented on docs/source/overview/using_dsh.md
> +
Could we bring in a SATRE reference here too?

e.g. For a comprehensive guide to the technical and organisational infrastructure required to fully support running of a DSH, see the [Standard Architecture for Trusted Research Environments (SATRE)](https://satre-specification.readthedocs.io/en/stable/)

2024-03-28 12:31 UTC, craddm commented on docs/source/roles/investigator/data_egress.md
> +Once you have finished working with the data for your project, you'll have to conduct the egress any outputs of your work before the environment is shutdown.
```suggestion
Once you have finished working with the data for your project, you'll have to conduct the egress of any outputs of your work before the environment is shutdown.
```

2024-03-28 12:32 UTC, craddm commented on docs/source/roles/project_manager/data_egress.md
> +Each time you egress data from the environment, it must be checked that it is safe and appropriate to release.
```suggestion
Each time you egress data from the environment, it must be checked to ensure that it is safe and appropriate to release.
```

2024-03-28 12:33 UTC, craddm commented on docs/source/roles/project_manager/data_ingress.md
> +At the end of this process they should have classified project into one of the Data Safe Haven security tiers.
```suggestion
At the end of this process they should have classified the project into one of the Data Safe Haven security tiers.
```

2024-03-28 12:35 UTC, craddm requested changes
Generally LGTM - a few comments above

2024-03-28 14:09 UTC, craddm approved these changes
LGTM!

2024-03-28 14:11 UTC, merged