Add test for help function
alan-turing-institute/data-safe-haven pull request #1855
Opened 2024-05-03 08:09 UTC by jemrobinson

## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).

### :arrow_heading_up: Summary

### :closed_umbrella: Related issues

Addresses point from #1853 review

### :microscope: Tests

Tested locally

2024-05-03 13:16 UTC, JimMadge requested changes

2024-05-03 13:16 UTC, JimMadge commented on data_safe_haven/cli.py
> +        application()()
Is there a reason to have this as a factory rather than a function?

2024-05-03 13:18 UTC, jemrobinson commented on data_safe_haven/cli.py
> +        application()()
If you want to make this change then you'll need to change the return type of `application` from `typer.Typer` to whatever a `typer.Typer()` is.

2024-05-03 13:28 UTC, JimMadge requested changes
In general, I don't like how `cli.py` is structured. It isn't very idiomatic typer.

I think it would be much clearer and easier to use if it followed the normal model of a `typer.Typer` object and `typer.Typer.command` decorators.

2024-05-03 13:29 UTC, jemrobinson commented
> In general, I don't like how `cli.py` is structured. It isn't very idiomatic typer.
> 
> I think it would be much clearer and easier to use if it followed the normal model of a `typer.Typer` object and `typer.Typer.command` decorators.

Are you happy to make that change on this PR?

2024-05-07 13:47 UTC, JimMadge approved these changes

2024-05-07 13:47 UTC, merged