Stop deployment from non-approved IP addresses
alan-turing-institute/data-safe-haven pull request #1977
Opened 2024-06-28 15:30 UTC by jemrobinson

## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

### :arrow_heading_up: Summary

ACLs can only be set/updated from approved admin IP addresses. This means that deploying from a non-admin IP address caused the deployment to fail. This PR catches the problem before deployment starts.

### :closed_umbrella: Related issues

Closes #1890

### :microscope: Tests

Tested locally.

2024-07-01 12:04 UTC, JimMadge requested changes
Looks good.

Would want to improve the coverage and see if we can reduce duplicate code.

2024-07-01 12:04 UTC, JimMadge commented on data_safe_haven/functions/network.py
> +    return ip_address
Let's add some tests for this.

2024-07-01 12:04 UTC, JimMadge commented on data_safe_haven/commands/sre.py
> +
As there are two instances of this, can we put it in a function?

Do we want to raise `typer.Exit` here?

2024-07-02 11:06 UTC, jemrobinson commented on data_safe_haven/functions/network.py
> +    return ip_address
Done in 80fdf3a

2024-07-02 12:17 UTC, jemrobinson commented on data_safe_haven/commands/sre.py
> +
Done in ac1ec310b.

I think it's unnecessary to raise a `typer.Exit`: this happens in a `try/except` block which will catch the error and raise `typer.Exit(1) from exc` after printing a "Could not deploy/teardown" message.

2024-07-03 15:12 UTC, JimMadge commented on pyproject.toml
> +  "requests-mock>=1.12",
Good find!

2024-07-03 15:13 UTC, JimMadge approved these changes

2024-07-03 15:15 UTC, merged