WIP Add Entra documentation
alan-turing-institute/data-safe-haven pull request #2039
Opened 2024-07-23 16:19 UTC by jemrobinson

## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

Document how to set up an Entra directory

### :closed_umbrella: Related issues

Closes #2025

### :microscope: Tests

Documentation only

2024-07-25 16:44 UTC, jemrobinson commented
**Note** We can change the default sign-in frequency from once every 90 days. Would once every day make sense?

2024-07-26 08:33 UTC, JimMadge commented
> **Note** We can change the default sign-in frequency from once every 90 days. Would once every day make sense?

That sounds sensible to me. Not frequent enough to be annoying. Frequent enough to make an unattended computer less of a risk.

2024-07-26 08:37 UTC, jemrobinson commented
<img width="297" alt="Screenshot 2024-07-26 at 09 36 35" src="https://github.com/user-attachments/assets/4405ecee-2ab5-4548-8f91-45144f840fbc">

Another option is "Every time"

> "Every time" option is evaluated on every sign-in attempt to an application in scope for this policy. Some policy configurations for the "sign-in frequency every time" session control are in preview.

2024-07-26 09:04 UTC, JimMadge requested changes
Looks good.

A few style changes and places to add some clarifying text.

I don't understand the usage of fixed width and bold, it feels inconsistent.
Do we have a place where we have said how/why we use them?

My preference would be to use emphasis over bold, bold sparingly and only use fixed width for code/variables/expressions.

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +        - If you have a choice of domains use `<your organisation>.onmicrosoft.com` which will create a clearer separation between administrators and users
```suggestion
        - If you have a choice of domains use `<your organisation>.onmicrosoft.com`, which will create a clearer separation between administrators and users
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +    - **User principal name:** `entra.admin.firstname.lastname`
```suggestion
    - **User principal name:** `entra.admin.<firstname>.<lastname>`
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +    - **Display name:** `Entra Admin - Firstname Lastname`
```suggestion
    - **Display name:** `Entra Admin - <Firstname> <Lastname>`
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- Click **Manage > Policies** on the internal menu on the left side.
```suggestion
- Browse to **Protection > Authentication methods** from the menu on the left side
- Click **Manage > Policies** on the internal menu on the left side
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- Go [here](https://passwordreset.microsoftonline.com/) and follow the instructions to set your password.
```suggestion
- Follow the instructions [here](https://passwordreset.microsoftonline.com/) to set your password
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- You will need access to the phone number and/or email address from the previous step.
```suggestion
- You will need access to the phone number and/or email address from the previous step
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +Start by identifying whether you have any external users
```suggestion
Start by identifying whether you have any external users.
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +P1 Licences are sufficient, but you may use another licence if you prefer.
```suggestion
P1 Licences are sufficient but you may use another licence if you prefer.
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- Click on `All products` on the internal menu on the left side.
```suggestion
- Browse to **Identity > Billing > Licenses** from the menu on the left side
- Click on `All products` on the internal menu on the left side
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- Under the option `Self service password reset enabled`, choose **All**.
```suggestion
- Browse to **Protection > Password reset** from the menu on the left side
- Click **Manage > Properties** on the internal menu on the left side
- Under the option `Self service password reset enabled`, choose **All**
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- Browse to **Identity > Overview > Properties** from the menu on the left side.
```suggestion
- Browse to **Identity > Overview > Properties** from the menu on the left side
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +- Click **Policies** on the internal menu on the left side.
```suggestion
- Browse to **Protection > Conditional Access** from the menu on the left side
- Click **Policies** on the internal menu on the left side
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +        - In the drop-down menu select `Global administrator`.
```suggestion
        - In the drop-down menu select `Global administrator`
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +
```suggestion
### Require MFA

These instructions will create a policy which requires all users (except the emergency administrator if you have created one) to use multi-factor authentication (MFA) to log in.

```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/deployment/configure_entra_id.md
> +
```suggestion
### Restrict Microsoft Entra ID access

These instructions will prevent non-administrators from being able to view the Entra ID configuration.

```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/management/index.md
> +Users created via the `dsh users` command line tool will be automatically registered for SSPR
```suggestion
Users created via the `dsh users` command line tool will be automatically registered for SSPR.
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/management/index.md
> +## Manually register users for SSPR
Is SSPR defined?

2024-07-26 09:04 UTC, JimMadge commented on docs/source/management/index.md
> +    - Phone: add the user's phone number with a space between the country code and the rest of the number (e.g. `+44 7700900000`).
```suggestion
    - Phone: add the user's phone number with a space between the country code and the rest of the number (_e.g._ `+44 7700900000`)
```

2024-07-26 09:04 UTC, JimMadge commented on docs/source/management/index.md
> +    - Ensure that you have registered **both** a phone number and an email address.
```suggestion
    - Ensure that you have registered **both** a phone number and an email address
```

2024-07-26 09:06 UTC, JimMadge commented
@jemrobinson I think every time would be annoying.

Perhaps this is something we want to leave open to users though. I could see it becoming appropriate for more sensitive information.

2024-07-26 09:09 UTC, JimMadge commented
These dropdown hints look great :+1:

2024-07-26 09:15 UTC, jemrobinson commented
> I don't understand the usage of fixed width and bold, it feels inconsistent.
> Do we have a place where we have said how/why we use them?

The Microsoft Entra docs use bold and > to indicate navigation through menus which I've tried to use here for consistency. It would be nice to use something (possibly fixed width?) to indicate things we want the user to select/type, but I don't know if I've been consistent with that. If you have a suggested style, I'm happy to change this PR to meet it.

2024-07-26 09:21 UTC, JimMadge commented
I think what bothers me the most is the inconsistently in **click me** and `click me`. How about,

- **bold** when we want to draw attention inline, user navigation or clicks
- *emph* foreign words and abbreviations
- `fixed width` code, expressions that the user types (`ls -l <path/to/directory>`), variable names

It will be easier to change later (if we want to) if we are as consistent as possible now.

2024-07-26 09:24 UTC, jemrobinson commented
[Google recommend](https://developers.google.com/style/placeholders) using uppercase characters with underscore delimiters. (*LIKE_THIS*) for text that you want the user to replace. I might try that in addition to your suggestions.

2024-07-26 09:38 UTC, jemrobinson commented on docs/source/management/index.md
> +## Manually register users for SSPR
```suggestion
## Manually register users for self-service password reset
```

2024-07-26 10:03 UTC, jemrobinson commented
Thanks for these suggestions @JimMadge : I think it already looks much better.

2024-07-26 10:07 UTC, JimMadge approved these changes

2024-07-26 10:25 UTC, jemrobinson commented
Just found out we can have semantic `menuselection` and `guilabel` attributes so I've added these.

2024-07-26 11:01 UTC, merged