Add validator for IP overlap
alan-turing-institute/data-safe-haven pull request #2087
Opened 2024-08-05 14:02 UTC by JimMadge

## :white_check_mark: Checklist

- [ ] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [ ] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [ ] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

### :arrow_heading_up: Summary

### :closed_umbrella: Related issues

Closes #2077 

### :microscope: Tests

2024-08-05 14:07 UTC, jemrobinson requested changes

2024-08-05 14:07 UTC, jemrobinson commented on data_safe_haven/config/config_sections.py
> +    def ensure_non_overlapping(cls, v: list[IpAddress]) -> list[IpAddress]:
This doesn't account for overlaps like `1.1.0.0/24` and `1.1.0.20/32`. This probably needs the functions in `IPv4Network` from `ipaddress`.

2024-08-05 14:13 UTC, JimMadge commented on data_safe_haven/config/config_sections.py
> +    def ensure_non_overlapping(cls, v: list[IpAddress]) -> list[IpAddress]:
Ah, thought that there were ip addresses not strings.

2024-08-05 14:13 UTC, jemrobinson commented on data_safe_haven/config/config_sections.py
> +    def ensure_non_overlapping(cls, v: list[IpAddress]) -> list[IpAddress]:
They are strings, but they're CIDRs. You will need to convert them to `IPv4Network`s then check for overlap.

2024-08-08 08:35 UTC, jemrobinson approved these changes
LGTM

2024-08-08 08:45 UTC, merged