Cleaner exit when user credentials are incorrect
alan-turing-institute/data-safe-haven pull request #2296
Opened 2024-11-15 16:09 UTC by craddm

## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

### :arrow_heading_up: Summary

When the user rejects the current credentials when asked to confirm they are correct, code would still continue to run, resulting in numerous additional, unnecessary and misleading error messages.

In addition, when the user rejects the Graph API credentials as incorrect, there is currently no clear way to *change* those credentials.
Graph API log-in is, unlike Az CLI log-in, not done by the user at the command line.

This PR simply exits when the user confirms that the credentials are incorrect, and prints only informative error messages. 
In addition, it advises the user how to remove the cached Graph API credentials so as to be able to login with other credentials. 

### :closed_umbrella: Related issues

Closes #2280 
Closes #2153 

### :microscope: Tests

Tested locally

2024-11-18 09:57 UTC, JimMadge requested changes, later dismissed
I don't think this is how we should solve this. We want to catch the problem and raise a suitable exception, which is handled by the command function.

2024-11-18 09:57 UTC, JimMadge commented on data_safe_haven/external/api/credentials.py
> +            raise typer.Exit(code=1) from exc
I don't think we should raise this exception anywhere except from Typer `command`s.

This module shouldn't depend on Typer.

2024-11-20 10:03 UTC, JimMadge commented
Example output

<img width="643" alt="Screenshot 2024-11-20 at 10 02 17" src="https://github.com/user-attachments/assets/2246c373-99ed-40f9-8d17-4903dd1097cb">

2024-11-20 11:09 UTC, JimMadge approved these changes
@craddm Could you take a look at this and say what you think?

I can't request a review from you as you opened the PR 😆

2024-11-20 12:13 UTC, craddm commented
LGTM

2024-11-20 13:48 UTC, merged